catalogoresgd/accounts/urls.py
# coding=utf-8

from django.conf.urls import url
from .views import *


urlpatterns =[
    url(r'^$', index_conta, name='index_conta'),
    url(r'^registro/$', registrar_usuario, name='registrar_user'),
    url(r'^alterar-dados/$', atualizar_usuario, name='atualizar_user'),
    url(r'^alterar-senha/$', atualizar_senha, name='atualizar_password'),

]

catalogoresgd/catalogo/urls.py
# coding=utf-8

from django.conf.urls import url
from .views import *


urlpatterns =[
    url(r'^profissionais/$', profissionais, name='profissionais'),
    url(r'^profissional/(?P<slug>[\w_-]+)/$', perfil_profissional, name='perfil_profissional'),
    url(r'^(?P<slug>[\w_-]+)/$', profissao, name='profissao'),

]

catalogoresgd/urls.py
# coding=utf-8

from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import login, logout
from catalogoresgd.core.views import *
from catalogoresgd.catalogo.views import *
from catalogoresgd.accounts.views import *

urlpatterns = [

    url(r'^$', index, name='home'),
    url(r'^sobre/$', sobre, name='sobre'),
    url(r'^contato/$', contato, name='contato'),

    # URL APP's
    url(r'^catalogo/', include('catalogoresgd.catalogo.urls', namespace='catalogo')),
    url(r'^conta/', include('catalogoresgd.accounts.urls', namespace='conta')),

    # URL AUTH
    url(r'^entrar/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^sair/$', logout, {'next_page': 'home'}, name='logout'),

    # URL ADMIN
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    #ou -> urlpatterns += static(
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

catalogoresgd/core/models.py
from django.db import models

# Create your models here.

catalogoresgd/core/forms.py
#coding=utf-8

from django import forms
from django.core.mail import send_mail
from django.conf import settings

class ContatoForm(forms.Form):
    nome = forms.CharField(label='Nome')
    email = forms.EmailField(label='E-mail')
    mensagem = forms.CharField(label='Mensagem', widget=forms.Textarea())

    def send_mail(self):
        nome = self.cleaned_data['nome']
        email = self.cleaned_data['email']
        mensagem = self.cleaned_data['mensagem']
        mensagem = 'Nome: {0}\nE-mail: {1}\nMensagem: {2}'.format(nome, email, mensagem)
        send_mail('Contato do Catalogo RESGD',
              mensagem,
              settings.DEFAULT_FROM_EMAIL,
              [settings.DEFAULT_FROM_EMAIL, email]
              )

    '''
        def __init__(self, *args, **kwargs):
            super(ContatoForm, self).__init__(*args, **kwargs)
            self.fields['nome'].widget.attrs['class'] = 'form-control'
            self.fields['email'].widget.attrs['class'] = 'form-control'
            self.fields['mensagem'].widget.attrs['class'] = 'form-control'
    '''

catalogoresgd/core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse_lazy
from .forms import ContatoForm


Usuario = get_user_model()

class IndexView(TemplateView):
    template_name = 'index.html'


class SobreView(TemplateView):
    template_name = 'sobre.html'


def contato(request):
    sucesso = False
    form = ContatoForm(request.POST or None)
    if form.is_valid():
        form.send_mail()
        sucesso = True
    context = {
        'form': form,
        'sucesso': sucesso,
    }
    return render(request, 'contato.html', context)


index = IndexView.as_view()
sobre = SobreView.as_view()

catalogoresgd/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <title>{% block title %}Catalogo RESGD{% endblock title %}</title>
    <link rel="icon" type="image/ico" href="{% static 'assets/favicon.ico' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link href="{% static 'assets/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/starter-template.css' %}" rel="stylesheet">
    <link href="{% static 'assets/custom.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/heroic-features.css' %}" media="screen" />
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a href="{% url 'home' %}" class="navbar-brand">Catalogo RESGD</a>
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'home' %}">Início</a>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">
                        Catalogo <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'catalogo:profissionais' %}">Tudo</a></li>
                        <li class="divider"></li>
                        {% for profissao in listar_profissoes %}
                            <li><a href="{{ profissao.get_absolute_url }}">{{ profissao.nome }}</a></li>
                        {% empty %}
                            <li>Ainda não existem serviços cadastrados</li>
                        {% endfor %}
                    </ul>
                </li>
                <li>
                    <a href="{% url 'sobre' %}">Sobre</a>
                </li>
                <li>
                    <a href="{% url 'contato' %}">Contato</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
              <li><a href="{% url 'conta:index_conta' %}">Conta</a></li>
              <li><a href="{% url 'logout' %}">Sair</a></li>
              {% else %}
              <li><a href="{% url 'login' %}">Entrar</a></li>
              <li><a href="{% url 'conta:registrar_user' %}">Registro</a></li>
              {% endif %}
              </ul>
        </div>
    </div>
</div>

<div class="container">
    {% block container %}{% endblock container %}
    <footer>
        <div class="raw">
            <div class="col-lg-12">
                <ul class="list-unstyled">
                    <li class="pull-right"><a href="#top">Voltar ao Topo</a></li>
                    <li><a href="{% url 'home' %}">Início</a></li>
                    <li><a href="{% url 'catalogo:profissionais' %}">Lista com todos os profissionais</a></li>
                    <li><a href="{% url 'sobre' %}">Sobre</a></li>
                    <li><a href="{% url 'contato' %}">Contato</a></li>
                    <li><a href="#">Termos e Privacidade</a></li>
                </ul>
                <p class="text-center" >Catalogo RESGD - Catalogo de Reparos & Serviços Gerais Domésticos - 2017 &copy; Todos os direitos reservados</p>
            </div>
        </div>
    </footer>
</div>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="{% static 'assets/bootstrap.min.js' %}"></script>
</body>
</html>

catalogoresgd/core/templates/contato.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
    Contato | {{ block.super }}
{% endblock title %}

{% block container %}
    <br>
    <div class="page-header">
        <h2>Fale conosco</h2>
        <hr>
        {% if sucesso %}
            <div class="alert alert-success">
                Mensagem enviada com sucesso
            </div>
        {% endif %}
        <form class="form-horizontal" action="" method="post">
            {% csrf_token %}
            <fieldset>
                {% for field in form %}
                    <div class="form-group{% if field.errors %} has-error {% endif %}">
                        <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                        <div class="col-md-9">
                            {% render_field field class='form-control' %}
                            {% for error in field.errors %}
                                <span class="help-block"> {{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        <button type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                </div>
            </fieldset>
        </form>
        {% comment %}
    <p> OU </p>
    <p class="lead">Você pode entrar em contato conosco pelas redes sociais.</p>
    <h5> Link: </h5>
    <ul>
        <li><strong>Rede social:</strong> Ainda não tem!!</li>
    </ul>
    {% endcomment %}
    </div>
{% endblock container %}

catalogoresgd/core/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Home | {{ block.super }}
{% endblock title %}

{% block container %}
    <div class="jumbotron page-header">
        <h2 class="text-info text-center">Catalogo RESGD - Catalogo de Reparos & Serviços Gerais Domésticos</h2>
        <br>
        <p>Site contem um catalogo com perfis de profissionais com experiencia na área de serviços voltados a construções e reparos de casas.</p>
        <p><a class="btn btn-primary btn-lg text-center" href="{% url 'sobre' %}">saiba mais...</a></p>
    </div>
{% endblock container %}

catalogoresgd/core/templates/login.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
    Login | {{ block.super }}
{% endblock title %}

{% block container %}
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="page-header">
                <h2>Entrar</h2>
            </div>
            <form class="form-horizontal" method="post">
                {% csrf_token %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ error }}
                    </div>
                {% endfor %}
                <fieldset>
                    <div class="form-group {% if form.username.errors %} has-error {% endif %}">
                        <label for="{{ form.username.auto_id }}" class="col-md-3 control-label">{{ form.username.label }}</label>
                        <div class="col-md-9">
                            {% render_field form.username class='form-control' %}
                            {% for error in form.username.errors %}
                                <span class="help-block"> {{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-group {% if form.password.errors %} has-error {% endif %}">
                        <label for="{{ form.password.auto_id }}" class="col-md-3 control-label">{{ form.password.label }}</label>
                        <div class="col-md-9">
                            {% render_field form.password class='form-control' %}
                            {% for error in form.password.errors %}
                                <span class="help-block"> {{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-9 col-md-offset-3">
                            <button type="submit" class="btn btn-primary">Enviar</button>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
{% endblock container %}

catalogoresgd/core/templates/pagination.html
    <div class="row">
        <div class="col-md-12">
            <nav>
                <ul class="pagination">
                    {% for page in paginator.page_range %}
                        <li {% if page_obj.number == page %} class="active"{% endif %}>
                            <a href="?page={{ page }}{{ getvars }}">{{ page }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </nav>
        </div>
    </div>

catalogoresgd/core/templates/sobre.html
{% extends 'base.html' %}

{% block title %}
    Sobre | {{ block.super }}
{% endblock title %}

{% block container %}
    <div class="jumbotron page-header">
        <h2> Sobre: </h2>
        <hr>
        <br>
        <p class="text-justify">Projeto de conclusão de curso.</p>
        <p class="text-info">O site contem um catalogo com perfis de profissionais com experiencia na área de serviços voltados para construções e reparos de casas.</p>
        <p><a href="https://github.com/diogogomes079/projeto_mono"> Código do GitHub</a> </p>
        <p class="text-warning">observação 1: os dados nesse site são apenas fictícios</h4>
        <p class="text-warning">observação 2: site ainda em construção</p>
    </div>
{% endblock container %}