catalogoresgd/accounts/urls.py
# coding=utf-8

from django.conf.urls import url
from .views import *


urlpatterns =[
    url(r'^$', index_conta, name='index_conta'),
    url(r'^registro/$', registrar_usuario, name='registrar_user'),
    url(r'^alterar-dados/$', atualizar_usuario, name='atualizar_user'),
    url(r'^alterar-senha/$', atualizar_senha, name='atualizar_password'),

]

catalogoresgd/urls.py
# coding=utf-8

from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import login, logout
from catalogoresgd.core.views import *
from catalogoresgd.catalogo.views import *
from catalogoresgd.accounts.views import *

urlpatterns = [

    url(r'^$', index, name='home'),
    url(r'^sobre/$', sobre, name='sobre'),
    url(r'^contato/$', contato, name='contato'),

    # URL APP's
    url(r'^catalogo/', include('catalogoresgd.catalogo.urls', namespace='catalogo')),
    url(r'^conta/', include('catalogoresgd.accounts.urls', namespace='conta')),

    # URL AUTH
    url(r'^entrar/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^sair/$', logout, {'next_page': 'home'}, name='logout'),

    # URL ADMIN
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    #ou -> urlpatterns += static(
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

catalogoresgd/accounts/models.py
# coding=utf-8

import re

from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin


class Usuario(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(
        'Apelido / Usuário', max_length=30, unique=True, validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'Informe um nome de usuário válido. '
                'Este valor deve conter apenas letras, números '
                'e os caracteres: @/./+/-/_ .'
                , 'invalid'
            )
        ], help_text='Um nome curto que será usado para identificá-lo de forma única na plataforma'
    )
    name = models.CharField('Nome', max_length=100, blank=True)
    email = models.EmailField('E-mail', unique=True)
    is_staff = models.BooleanField('Equipe', default=False)
    is_active = models.BooleanField('Ativo', default=True)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.name or self.username

    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        return str(self).split(" ")[0]

catalogoresgd/accounts/forms.py
# coding=utf-8

from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Usuario

class UsuarioAdminCreationForm(UserCreationForm):

    class Meta:
        model = Usuario
        fields = ['username', 'name', 'email']


class UsuarioAdminForm(forms.ModelForm):

    class Meta:
        model = Usuario
        fields = ['username', 'name', 'email', 'is_active', 'is_staff']

catalogoresgd/accounts/views.py
# coding=utf-8

from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView, FormView

from .forms import UsuarioAdminCreationForm
from .models import Usuario


class IndexContaView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/conta_usuario.html'


class RegistroView(CreateView):
    model = Usuario
    template_name = 'accounts/cadastrar_usuario.html'
    form_class = UsuarioAdminCreationForm
    success_url = reverse_lazy('home')


class AtualizarUsuarioView(LoginRequiredMixin, UpdateView):

    model = Usuario
    template_name = 'accounts/atualizar_usuario.html'
    fields = ['name', 'email']
    success_url = reverse_lazy('conta:index_conta')

    def get_object(self):
        return self.request.user


class AtualizarSenhaView(LoginRequiredMixin, FormView):

    template_name = 'accounts/atualizar_senha.html'
    success_url = reverse_lazy('conta:index_conta')
    form_class = PasswordChangeForm
    def get_form_kwargs(self):
        kwarg = super(AtualizarSenhaView, self).get_form_kwargs()
        kwarg['user'] = self.request.user
        return kwarg

index_conta = IndexContaView.as_view()
registrar_usuario = RegistroView.as_view()
atualizar_usuario = AtualizarUsuarioView.as_view()
atualizar_senha = AtualizarSenhaView.as_view()

catalogoresgd/accounts/templates/accounts/atualizar_senha.html
{% extends 'accounts/conta_usuario.html' %}

{% load widget_tweaks %}

{% block title %} Alterar Senha {% endblock title %}

{% block accounts_container %}
    <h2>Alterar Senha</h2>
    <form class="form-horizontal" method="post">
        {% csrf_token %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
        {% endfor %}
        <fieldset>
            {% for field in form %}
                <div class="form-group {% if field.errors %} has-error {% endif %}">
                    <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                    <div class="col-md-9">
                        {% render_field field class='form-control' %}
                        {% for error in field.errors %}
                            <span class="help-block"> {{ error }}</span>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
            <div class="form-group">
                <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </div>
            </div>
        </fieldset>
    </form>
{% endblock accounts_container %}

catalogoresgd/accounts/templates/accounts/atualizar_usuario.html
{% extends 'accounts/conta_usuario.html' %}

{% load widget_tweaks %}

{% block title %}
    Alterar dados
{% endblock title %}

{% block accounts_container %}
    <h2>Alterar Dados</h2>
    <form class="form-horizontal" method="post">
        {% csrf_token %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
        {% endfor %}
        <fieldset>
            {% for field in form %}
                <div class="form-group {% if field.errors %} has-error {% endif %}">
                    <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                    <div class="col-md-9">
                        {% render_field field class='form-control' %}
                        {% for error in field.errors %}
                            <span class="help-block"> {{ error }}</span>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
            <div class="form-group">
                <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </div>
            </div>
        </fieldset>
    </form>
{% endblock accounts_container %}

catalogoresgd/accounts/templates/accounts/cadastrar_usuario.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
    Registro | {{ block.super }}
{% endblock title %}

{% block container %}
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="page-header">
                <h2>Registro</h2>
            </div>
            <form class="form-horizontal" method="post">
                {% csrf_token %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ error }}
                    </div>
                {% endfor %}
                <fieldset>
                {% for field in form %}
                    <div class="form-group {% if field.errors %} has-error {% endif %}">
                        <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                        <div class="col-md-9">
                            {% render_field field class='form-control' %}
                            {% for error in field.errors %}
                                <span class="help-block"> {{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
                    <div class="form-group">
                        <div class="col-md-9 col-md-offset-3">
                            <button type="submit" class="btn btn-primary">Registrar</button>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
{% endblock container %}

catalogoresgd/accounts/templates/accounts/conta_usuario.html
{% extends 'base.html' %}

{% block title %}
    Minha Conta | {{ block.super }}
{% endblock title %}

{% block container %}
    <div class="container">
        <div class="row">
            <br>
            <ol class="breadcrumb">
                <li><a href="{% url 'conta:index_conta' %}">Início</a></li>
                <li class="active">Minha Conta</li>
            </ol>
            <div class="row">
                <div class="col-md-4">
                    <div class="list-group">
                        <a href="#" class="list-group-item active">Minha Conta</a>
                        <a href="{% url 'conta:atualizar_user' %}" class="list-group-item">Alterar Dados</a>
                        <a href="{% url 'conta:atualizar_password' %}" class="list-group-item">Alterar Senha</a>
                    </div>
                </div>
                <div class="col-md-8">
                    {% block accounts_container %}
                        <h2>Bem vindo {{ user }}</h2>
                    {% endblock accounts_container %}

                </div>
            </div>
        </div>
    </div>
{% endblock container %}